### ISSUE TITLE
phiên bản hiện tại không hoạt động

### ISSUE THREAD

**Issue by TienDat2k** [alvin0319/SimpleMapRenderer#5]
plugin không hoạt động khi tôi khởi động máy chủ. bạn có thể cập nhật không ?

**Comment by alvin0319** [comment]
Please use english.

**Comment by TienDat2k** [comment]
Can you update it to fit the current pocketmine API? Because I can't use it because it says this version doesn't work

**Comment by TienDat2k** [comment]
![image](https://user-images.githubusercontent.com/88370821/133047047-823a9a0a-3da8-4909-99a4-8575e1df159d.png)
